
## compose.yaml
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns --default-artifact-root /mlruns
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5000:5000"

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./:/app

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_MODEL_URI=models:/telco-churn-classifier/None
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./:/app
