---

## .github/workflows/cd.yml


name: CD
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/telco-churn-app:latest

---

